version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "autoupdate"
    open-pull-requests-limit: 100
    groups:
      sentry:
        patterns:
          - "@sentry/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "autoupdate"
