name: Lint documentation

on:
  push:
    branches:
      - main
      - internal
  pull_request:
  workflow_dispatch:

jobs:
  vale-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vale
        run: |
          curl -fsSL https://github.com/errata-ai/vale/releases/download/v3.12.0/vale_3.12.0_Linux_64-bit.tar.gz | tar xz
          sudo mv vale /usr/local/bin/

      - name: Run Vale on docs
        id: vale
        run: |
          OUTPUT=$(vale --glob='docs/**' --minAlertLevel=suggestion .)
          echo "$OUTPUT"
          echo "$OUTPUT" > vale_output.txt
          if ! grep -q "0 errors, 0 warnings and 0 suggestions" vale_output.txt; then
            echo "Vale found issues in the documentation."
            exit 1
          fi