name: Versioning

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: build-gradle
        uses: juliangruber/read-file-action@v1
        with:
          path: ./android/app/build.gradle

      - uses: actions-ecosystem/action-regex-match@v2
        id: version-code
        with:
          text: ${{ steps.build-gradle.outputs.content }}
          regex: 'versionCode (.*)'

      - uses: actions-ecosystem/action-regex-match@v2
        id: version-name
        with:
          text: ${{ steps.build-gradle.outputs.content }}
          regex: 'versionName "(.*)"'

      - name: Echo versionCode
        run: echo "${{ steps.version-code.outputs.group1 }}"

      - name: Echo versionName
        run: echo "${{ steps.version-name.outputs.group1 }}"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: "${{ steps.version-name.outputs.group1 }}.${{ steps.version-code.outputs.group1 }}"
          tag_prefix: ""